[package]
name = "cubix-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
heed = "0.22.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
clap = { version = "4.5.35", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
thiserror = "1.0.69"
